name = "ExamplePkg"
uuid = "32b2df20-07df-432a-9b4b-6cda8a62f240"
authors = ["S. Jean Feeser <sjfeeser@psu.edu>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Distributions = "0.25.122"
Test = "1.11.0"
